#!/usr/bin/env bash
# itds.sh — interactive / scriptable network helper
# v2.0 — adds multiple scan modes, presets, traceroute, http check, output file, interactive mode
#
# Examples:
#   ./itds.sh -n -t -i google.com -p 80     # nmap + ping on port 80
#   ./itds.sh -N syn -i 192.168.1.1 -P common -o scan.txt
#   ./itds.sh -I                              # interactive mode
#   ./itds.sh -T -i example.com               # traceroute
#
# Features:
# - ping, nmap (multiple scan types), traceroute, http(S) quick check
# - presets for common ports (common, web, ssh)
# - save results to timestamped output files
# - interactive mode (menu-driven) or CLI-only mode
# - dependency checks and helpful errors
# - safe checks (warn if SYN scan without root)
# - verbose / quiet modes
#
set -o errexit
set -o nounset
set -o pipefail

PROGNAME="$(basename "$0")"
VERSION="2.0"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TIMESTAMP="$(date +%Y%m%d_%H%M%S)"

# defaults
do_nmap=0
do_ping=0
do_traceroute=0
do_http=0
interactive=0
scan_type="connect"   # connect, syn, udp, service (version)
target=""
ports=""
ping_count=5
timeout=30            # general timeout for network tools (where supported)
output_dir="$BASEDIR/itds_output"
outfile=""
verbose=1

# Port presets
declare -A PRESETS
PRESETS[common]="22,80,443,3389,3306,53"
PRESETS[web]="80,443,8080,8443"
PRESETS[ssh]="22"
PRESETS[top100]="1-1024"

# helper prints
info() { [ "$verbose" -eq 1 ] && printf '[*] %s\n' "$*"; }
warn() { printf '[!] %s\n' "$*" >&2; }
err() { printf 'Error: %s\n' "$*" >&2; exit 2; }
die() { err "$*"; }

show_usage() {
  cat <<EOF
$PROGNAME $VERSION

Usage: $PROGNAME [options]

Actions (at least one required):
  -n             Run nmap (enable nmap actions)
  -t             Ping the target
  -T             Traceroute to target
  -H             Quick HTTP(S) check (curl)
  -I             Interactive menu mode (overrides some flags)

Nmap options:
  -N <mode>      nmap scan type: connect|syn|udp|service  (default: connect)
  -p <ports>     Port(s) for nmap. Single, comma-list, or range (e.g. 22,80 or 1-1024)
  -P <preset>    Port preset name (common, web, ssh, top100). Overrides -p.

General:
  -i <target>    Target IP or hostname (required for network actions)
  -c <count>     Ping count (default: 5)
  -o <file>      Write combined output to file (if omitted, autogenerated file is used)
  -d <dir>       Output directory (default: ./itds_output)
  -q             Quiet (less output)
  -v             Verbose (more output)
  -V             Print version and exit
  -h             Show this help and exit

Examples:
  $PROGNAME -n -t -i google.com -p 80
  $PROGNAME -n -N syn -i 10.0.0.5 -P web -o out.txt
  $PROGNAME -I

EOF
}

# parse args
while getopts ":nti:p:P:c:o:d:N:IHqvVh" opt; do
  case "$opt" in
    n) do_nmap=1 ;;
    t) do_ping=1 ;;
    T) do_traceroute=1 ;;
    H) do_http=1 ;;
    I) interactive=1 ;;
    i) target="$OPTARG" ;;
    p) ports="$OPTARG" ;;
    P) preset="$OPTARG"
       if [ -n "${PRESETS[$preset]:-}" ]; then
         ports="${PRESETS[$preset]}"
       else
         err "Unknown preset: $preset. Available: ${!PRESETS[*]}"
       fi
       ;;
    c) 
       if ! [[ "$OPTARG" =~ ^[0-9]+$ ]]; then die "Invalid ping count: $OPTARG"; fi
       ping_count="$OPTARG"
       do_ping=1
       ;;
    o) outfile="$OPTARG" ;;
    d) output_dir="$OPTARG" ;;
    N) scan_type="$OPTARG" ;;
    q) verbose=0 ;;
    v) verbose=1 ;;
    V) printf '%s\n' "$VERSION"; exit 0 ;;
    h) show_usage; exit 0 ;;
    :) die "Option -$OPTARG requires an argument." ;;
    \?) die "Invalid option: -$OPTARG" ;;
  esac
done

# basic validation
if [ "$interactive" -eq 0 ]; then
  if [ "$do_nmap" -eq 0 ] && [ "$do_ping" -eq 0 ] && [ "$do_traceroute" -eq 0 ] && [ "$do_http" -eq 0 ]; then
    err "No action requested. Use -n, -t, -T, -H or -I."
    show_usage
    exit 2
  fi
  if { [ "$do_nmap" -eq 1 ] || [ "$do_ping" -eq 1 ] || [ "$do_traceroute" -eq 1 ] || [ "$do_http" -eq 1 ]; } && [ -z "$target" ]; then
    err "Target (-i) is required unless running interactive mode (-I)."
    show_usage
    exit 2
  fi
fi

# ensure output dir
mkdir -p "$output_dir"
if [ -z "$outfile" ]; then
  outfile="$output_dir/${target:-interactive}_$TIMESTAMP.txt"
fi

# dependency checks
ensure_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    warn "Required command '$1' not found in PATH. Some features may be unavailable."
    return 1
  fi
  return 0
}

# interactive menu
interactive_menu() {
  echo "=== itds interactive mode ==="
  PS3="Choose an action: "
  options=("Ping" "Nmap (quick)" "Traceroute" "HTTP check" "Full scan (nmap+ping)" "Quit")
  select opt in "${options[@]}"; do
    case $REPLY in
      1)
        read -rp "Target: " target
        do_ping=1
        ping_host
        ;;
      2)
        read -rp "Target: " target
        read -rp "Ports (or preset name like 'web'/'common'): " pres
        if [ -n "${PRESETS[$pres]:-}" ]; then ports="${PRESETS[$pres]}"; else ports="$pres"; fi
        do_nmap=1
        scan_type="connect"
        run_nmap
        ;;
      3)
        read -rp "Target: " target
        do_traceroute=1
        traceroute_host
        ;;
      4)
        read -rp "Target: " target
        do_http=1
        http_check
        ;;
      5)
        read -rp "Target: " target
        read -rp "Ports (or preset): " pres
        if [ -n "${PRESETS[$pres]:-}" ]; then ports="${PRESETS[$pres]}"; else ports="$pres"; fi
        do_nmap=1; do_ping=1
        run_nmap; ping_host
        ;;
      6) echo "bye"; break ;;
      *) echo "invalid option";;
    esac
  done
  exit 0
}

# small helpers
root_check() {
  if [ "$(id -u)" -ne 0 ]; then
    return 1
  fi
  return 0
}

append_output() {
  # nice header for each section
  printf '\n==== %s: %s ====\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$1" | tee -a "$outfile"
  # second arg is command to run (as string)
  shift
  if [ "$#" -gt 0 ]; then
    eval "$@" 2>&1 | tee -a "$outfile"
  fi
}

# actions
ping_host() {
  ensure_cmd ping >/dev/null || { warn "ping not available — skipping ping"; return; }
  info "PING: sending $ping_count packets to $target"
  append_output "PING $target" ping -c "$ping_count" -W 5 "$target" || warn "Ping returned non-zero"
}

traceroute_host() {
  # try traceroute, then tracepath
  if ensure_cmd traceroute >/dev/null; then
    info "Traceroute via traceroute"
    append_output "TRACEROUTE $target" traceroute -m 30 "$target" || warn "Traceroute non-zero exit"
  elif ensure_cmd tracepath >/dev/null; then
    info "Traceroute via tracepath"
    append_output "TRACEPATH $target" tracepath "$target" || warn "Tracepath non-zero exit"
  else
    warn "No traceroute/tracepath command found; install traceroute package."
  fi
}

http_check() {
  if ! ensure_cmd curl >/dev/null; then
    warn "curl not found; skipping HTTP check."
    return
  fi
  info "HTTP check: GET https://$target and http://$target (if reachable)"
  append_output "HTTP (https) $target" curl -I --max-time 10 "https://$target" || warn "HTTPS check failed"
  append_output "HTTP (http) $target" curl -I --max-time 10 "http://$target" || warn "HTTP check failed"
}

run_nmap() {
  if ! ensure_cmd nmap >/dev/null; then
    warn "nmap missing; cannot run nmap actions."
    return
  fi

  if [ -z "$ports" ]; then
    warn "No ports specified for nmap; defaulting to preset 'common'"
    ports="${PRESETS[common]}"
  fi

  # pick nmap flags based on scan_type
  case "$scan_type" in
    connect)
      nmap_flags="-sT -Pn"
      ;;
    syn)
      nmap_flags="-sS -Pn"
      if ! root_check; then
        warn "SYN scans (-sS) typically require root. Running might fail or be slower; switch to connect (-sT) or run as root."
      fi
      ;;
    udp)
      nmap_flags="-sU -Pn"
      ;;
    service)
      nmap_flags="-sS -sV -O -Pn"
      if ! root_check; then
        warn "Service/OS detection may be limited when not run as root."
      fi
      ;;
    *)
      warn "Unknown scan_type: $scan_type. Using connect scan."
      nmap_flags="-sT -Pn"
      ;;
  esac

  info "NMAP: $scan_type scan on $target ports: $ports"
  append_output "NMAP $target ($scan_type)" nmap $nmap_flags -p "$ports" --host-timeout "${timeout}s" "$target" || warn "nmap returned non-zero"
}

# composite runs
full_scan() {
  run_nmap
  ping_host
  http_check
  traceroute_host
}

# run
main() {
  info "Output file: $outfile"
  append_output "RUN START" printf "itds v%s\nTarget: %s\nActions: nmap=%s ping=%s traceroute=%s http=%s\nPorts: %s\nScan type: %s\n\n" "$VERSION" "${target:-interactive}" "$do_nmap" "$do_ping" "$do_traceroute" "$do_http" "${ports:-(none)}" "$scan_type"

  if [ "$do_ping" -eq 1 ]; then
    ping_host
  fi

  if [ "$do_nmap" -eq 1 ]; then
    run_nmap
  fi

  if [ "$do_http" -eq 1 ]; then
    http_check
  fi

  if [ "$do_traceroute" -eq 1 ]; then
    traceroute_host
  fi

  append_output "RUN END" printf "Completed at %s\n" "$(date '+%Y-%m-%d %H:%M:%S')"
  info "Results saved to: $outfile"
}

# If interactive requested, start the menu
if [ "$interactive" -eq 1 ]; then
  interactive_menu
fi

main
exit 0
